### ISSUE TITLE
Ausgabe des Vips-Aufgaben- Feedbacks

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#101]
In Vips kann bereits Feedback für Aufgaben hinterlegt werden. Dieses soll zusammen mit der Lösung einer Selbsttestaufgabe auch angezeigt werden können. Gleiches gilt für Hinweise.

**Comment by tthelen** [comment]
Der Hinweis sollte nicht automatisch, sondern nur nach Klick ausgegeben werden! (Auf- und Zuklappen)
