### ISSUE TITLE
Textblock nicht auswerten, Vergleich mit Musterlösung

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#104]
Für Selbsttest-Aufgaben , die nicht automatisch ausgewertet werden können, soll eine Musterlösung als Vergleich angezeigt werden können. (z.B. Textbox-Aufgaben).

**Comment by tthelen** [comment]
"Ihre Lösung ist nicht korrekt" ist natürlich hier keine sinnvolle Einblendung. Lässt sich das umgehen? Ebenso die Anzahl der VErsuche - die richtige Lösung sollte immer nach dem ersten Einreichen angezeigt werden.
