### ISSUE TITLE
Quellcode-Block mit Syntax (highlight.js)

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#105]
Über einen speziellen Block-Typ soll Programm-Quelltext mit Syntax-Highlighting und Download-Möglichkeit angezeigt werden können. Dazu soll die Javascript-Bibliothek highlight.js verwendet werden.

**Comment by rlucke** [comment]
Wie soll die Download-Möglichkeit aussehen?

**Comment by tthelen** [comment]
Der Inhalt des Feldes wird mit separatem Request als text/plain mit dem Header 

Content-Disposition: attachment; filename="<string from block's filename field>"

gesendet.
