### ISSUE TITLE
Courseware für nobody frei zugänglich 

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#111]
Kurse sollen auch ohne Anmeldung zugänglich sein können, also für Rechtestufe nobody lesbar. Selbsttest-Aufgaben sollen lösbar sein, Kommentare, Übungsaufgaben und Klausuren und andere aktive
Inhalte nur lesbar. Noch zu diskutieren: Dann angezeigter Navigationskontext, Verbindung zu Mooc.IP Open Courses.

**Comment by luniki** [comment]
Abgeschätzt sind 9 PT. Aus diesem Grund wird dieses Issue aufgeteilt:

- in einem Issue wird der strukturelle Unterbau entsprechend angepasst (5 PT)
- in einem zweiten Issue werden die einzelnen Inhaltsblöcke darauf abgestimmt (4 + TestBlock PT)

**Comment by luniki** [comment]
Dieses Issue wird zur Koordination verwendet.
