### ISSUE TITLE
Didaktische Absatztypen (Merksatz, Beispiel, ...)

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#112]
courseware-Texte sollen besondere Absatzmarkierungen bekommen können: Merksatz, Warnung, Weiterführende Informationen, ... Die Absätze sollen durch eine charakteristische Hintergrundfarbe und ein Icon gekennzeichnet werden. Voraussatzung für diese Änderung ist die separate Wysiwyg-Konfiguration für Courseware.

**Comment by tthelen** [comment]
Einfachere Idee: Das sind nicht Absatztypen, die im Editor eingestellt werden, sondern Eigenschaften von Textblöcken, um z.B. einen kompletten Block als Beispiel, Hinweis, Defintion etc. zu markieren. Beispiel: https://storage.spec.whatwg.org/#terminology

**Comment by rlucke** [comment]
Um zu schauen wie ein solcher Block angenommen wird, habe ich einen neuen Blocktypen namens KeyPointBlock (Merksatz) erstellt. Dieser kann einen beliebigen kurzen Text ausgeben. Ein Icon vor dem Text sowie Umrandungs- und Iconfarbe können ausgewählt werden. (15 Icons und 5 Farben)

**Comment by tthelen** [comment]
Die Icons sollten in der Drop-Downliste sichtbar sein, die dort verwendeten Namen einheitlicher machen ( 1) Groß- und Kleinschreibung, b) aussagekräftige Namen gleichen Typs (z.B. nur Verben)).

Eingabefeld für Merksatz bitte Wysiwyg
