### ISSUE TITLE
Umstellung von requirejs auf webpack

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#118]

**Comment by luniki** [comment]
Wird gerade im branch https://github.com/virtUOS/courseware/tree/webpack fertiggestellt

**Comment by rlucke** [comment]
Kannst du bitte, wenn die Arbeiten im webpack Branch fertig sind, die Änderungen in den develop22 Branch mergen.

**Comment by luniki** [comment]
Die sind schon fertig. Kannst also den einen Commit direkt in webpack reinspielen.
