### ISSUE TITLE
Neuer Bildergalerieblock nicht löschbar

### ISSUE THREAD

**Issue by tthelen** [virtUOS/courseware#130]
In meinem Testsystem (Stud.IP 3.5 / Firefox haben neue Bildergalerie-Blöcke keinen Inhalte und sind weder lösch- noch bearbeitbar. Dies steht im HTML:

<section id="block-31" class="block GalleryBlock loading" data-blockid="31" data-blocktype="GalleryBlock">

  <div class="controls editable">
    <span class="type">
                    Galerie
                </span>

    <button class="lower">Absenken</button>
    <button class="raise">Anheben</button>
    <button class="author" style="display: inline-block;">Ändern</button>
    <button class="trash">Entfernen</button>
  </div>

  
<div class="block-content" data-view="student"><input name="gallery-autoplay" value="" type="hidden">
<input name="gallery-autoplay-timer" value="" type="hidden">
<input name="gallery-hidenav" value="" type="hidden">
<div class="cw-gallery">

</div>

    <div class="messagebox messagebox_info answerinfo">
        In dem ausgewählten Ordner befinden sich keine Bilder. 
    </div>
</div></section>

re #113

**Comment by rlucke** [comment]
Wie so meist lag der Fehler im Detail. In der student_view fehlte in Zeile 24 ein "this".

**Comment by tthelen** [comment]
behebt den Fehler aber nicht
