### ISSUE TITLE
Sidebar wird abgeschnitten und verhält sich nicht wie die anderen Sidebars

### ISSUE THREAD

**Issue by Davka** [virtUOS/courseware#137]
![screenshot 2018-02-20 08 29 50](https://user-images.githubusercontent.com/1117697/36411947-3a7f2572-1618-11e8-81b2-944f7e5926eb.png)

**Comment by rlucke** [comment]
Die Sidebar der Courseware ist nicht die Sidebar von Stud.IP! 
Da es in 3.0 eine viele neue Elemente gibt wurde auf die alten Button verzichtete und eine Navigation erschaffen die an die Stud.IP Sidebar angelehnt ist.
