### ISSUE TITLE
Dozent bzw. Tutor -> Kommentare ausblenden / verstecken 

### ISSUE THREAD

**Issue by t001** [virtUOS/courseware#140]
Diskussionsübersicht -> Admins sollten Kommentare ausblenden können

Teilnehmerinnnen können Kommentare wie Muserlösungen oder auch Verbotene Kommentare abgeben, der Dozent bzw. Tutor sollte das Recht bekommen die Kommentare auszublenden

**Comment by rlucke** [comment]
fixed in 3.0.7 and 4.0.7
