### ISSUE TITLE
Freitext bearbeiten kaputt?

### ISSUE THREAD

**Issue by asudau** [virtUOS/courseware#147]

**Comment by asudau** [comment]
in den versionen 3.0.6 - 3.1.0 (vom marktplatz)  kann ich keinen freitext editieren (bei dpeichern passier nix und es gibt nen javascriptfehler in der konsole) habe mir jetzt ne 3.0.4 geholt, da gehts (3.0.5 hab ich nicht getestet)

studip version 3.5.5 (aber das spielt wohl eher keine rolle)

**Comment by jasperroloff** [comment]
Hallo, ich hatte scheinbar das gleiche Problem. Das Aktivieren von "WYSIWYG" in der Systemkonfiguration von Stud.IP hat es in meinem Fall gelöst.
