### ISSUE TITLE
Löschen Button enthält Text

### ISSUE THREAD

**Issue by Askill** [virtUOS/courseware#148]
Der Löschen Button eines Abschnittes hat Text im Button tag der geklickt werden kann, das kann zu fehlerhaftem löschen führen.

**Comment by rlucke** [comment]
Wie sieht denn fehlerhaftes löschen aus?

**Comment by Askill** [comment]
Der Text des button geht über den eigentlichen Button hinaus, wenn man also auf eine eigentlich leere Fläche klickt klickt man tatsächlich auf den Löschen Button.
