### ISSUE TITLE
Manifest ist veraltet / Git Daten ungleich dev.studip Daten

### ISSUE THREAD

**Issue by Askill** [virtUOS/courseware#151]
Im Manifest steht noch stupid 3.5, statt 4.1.
Beim clonen der 4.1 getagten variante und befolgen der Installationsanweisungen kommt es zu einer fehlerhaften Anzeige im StudIP.

**Comment by rlucke** [comment]
Es gibt zwei Courseware Versionen! Eine für die 3er StudIPs und eine für die 4er!
