### ISSUE TITLE
Fortschrittsbalken reseten

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#157]
Wenn Lehrende die Kapitel und Abschnitte anlegen und testen, dann wird das im Fortschritt schon berücksichtigt. Man sollte die Möglichkeit haben, den Fortschritt zu reseten.

**Comment by asudau** [comment]
du meinst dann den Fortschritt des Dozenten? Der tauch doch in der Fortschrittsübersicht gar nicht auf oder?

**Comment by nimuelle** [comment]
Der Wunsch kam wohl, als ein Lehrender etwas angelegt hat und er mit seinem Studentenzugang auch schon gleich getestet hatte. Vielleicht hatter er auch 2-3 Studis gesagt, sich das mal anzuschauen und zu testen. 
Als es dann richtig losgehen sollte, waren dann schon Fortschritte sichtbar.
Daher kam uns die Idee, ob man als Lehrende einfach die Möglichkeit hat, den Fortschritt zu reseten. Man kann ja eplizit nachfragen, ob man das wirklich will.

**Comment by asudau** [comment]
ah ok, das heißt dann dass der Dozent den Fortschritt einzelner Studierenden resetet und nicht seinen eigenen, verstehe!

**Comment by asudau** [comment]
achso oder vllt der Student einfach seinen eigenen..

**Comment by asudau** [comment]
wir haben gerade rausgefunden dass es das schon gibt (also für studierende) ist bloß noch nicht im release :-)
