### ISSUE TITLE
Einstellungen: Blocktypen kursweit de/aktivieren können

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#16]
Um den Diskussionsblocktyp einbauen zu können, benötigt man einen Ort zum Speichern der Aktivierung. Irgendwo muss also stehen, dass in einer spezifischen Courseware ein bestimmter Blocktyp aktiv/inaktiv ist. 

Ideen, wo das stehen könnte:

- Stud.IP Datenfeld für Veranstaltungen: gäbe es dann aber auch für VAs ohne Courseware
- Courseware-Block-Scope-Field: das wäre vermutlich zu dynamisch für etwas, was man eigentlich häufig braucht
- neue Datenstruktur

**Comment by tthelen** [comment]
Braucht man nicht häufiger mal globale Einstellungen für Plugins? Wo wird denn gespeichert, wie der Matterhorn-Server heißt? 

Könnte man generische Datenfelder für Plugins bauen?

**Comment by xabbuh** [comment]
@tthelen Globale Einstellungen stehen in der Config. Die sind dann aber nicht kursspezifisch.

**Comment by luniki** [comment]
Ich teste gerade die Möglichkeit "Courseware-Block-Scope-Field". Dabei fallen zwei Probleme auf:

- Die Courseware muss plötzlich DiscussionBlock-spezifisches Wissen haben (Blubber muss gleichzeitig aktiviert werden.)
- In DiscussionBlock#additionalInstanceAllowed komme ich nicht ohne weiteres an die Courseware heran.

Diese Lösung scheint mir nicht die geeigneteste zu sein, ich baue sie aber dennoch zuerst ein und prüfe dann die Alternativen.

**Comment by luniki** [comment]
Außerdem muss schon in der Plugin-Klasse selbst entscheidbar sein, ob der DiscussionBlock angezeigt werden soll oder nicht. An der Stelle bereits den Courseware-Block zu erzeugen, ist definitiv nicht der richtige Weg.
