### ISSUE TITLE
Diagrammblock - Datenbezeichnung

### ISSUE THREAD

**Issue by asudau** [virtUOS/courseware#160]
für den Diagrammblock kann ich einmalig eine Datenbezeichnung auswählen, diese erfüllt im Grunde den Zweck der Diagrammüberschift, wird aber stattdessen bei Mouseover für jede einzelne Säule angezeigt (mit nem Doppelpunkt dahinter und dann dem Wert der Säule). 

Ich finde das macht nicht soviel Sinn bzw. würde es sogar für einen Bug halten.. Ich hätte sie stattdessen gerne als Überschrift obendrüber..

Und wo ich schon dabei bin, optionale Einheiten wären super (also zB. %), kann ich ja zentral einmal einstellen für das Diagramm..

![grafik](https://user-images.githubusercontent.com/11834384/54359674-7038fb80-4663-11e9-8833-bf057cec6117.png)

![grafik](https://user-images.githubusercontent.com/11834384/54359687-7dee8100-4663-11e9-916e-023ede357bdb.png)

**Comment by rlucke** [comment]
;)

**Comment by asudau** [comment]
ey :-P ich bin nicht qualifiziert ^^

**Comment by rlucke** [comment]
partly fixed
