### ISSUE TITLE
Layout Gruppierungsblock

### ISSUE THREAD

**Issue by asudau** [virtUOS/courseware#161]
ist das kaputtgegangen? Hier im Studentenmodus.. sieht irgendwie komisch aus, müssten die akkoreondbalken nicht ein dunkleres Blau sein?

![grafik](https://user-images.githubusercontent.com/11834384/54360539-5b5d6780-4665-11e9-9875-d3f3ba34d565.png)

**Comment by rlucke** [comment]
Meinst du das StudIP blau (#28497c) als Hintergrund für die Balken?

**Comment by asudau** [comment]
hmm ich bin grad etwas verunsichert ich glaube ich kannte das nur in DFB grün :-P
aber ich wäre für etwas mehr abstand zwischen text und pfeil ^^
hab mal in die alte courseware auf eL4 geguckt: 

![grafik](https://user-images.githubusercontent.com/11834384/54366208-8c8f6500-4670-11e9-9f69-47edcacb2c09.png)
