### ISSUE TITLE
gruppieren - reihenfolge

### ISSUE THREAD

**Issue by asudau** [virtUOS/courseware#162]
da hab ich mal ne Frage. Die Editieransicht hat sich glaub ich etwas geändert. Ich sehe jetzt einmel die Vorschau auf z.B: das Accordeon und gleichzeiti mit gestricheltem Rahmen die Blöche welche gruppiert wurden (falls ich die nochmal bearbeiten will)

Ich kann jetzt die einzelnen Blöcke in ihrer Reihenfolge verschieben, das wirkt sich jedoch im Nachhinein nicht auf die Reihenfole im Accordeon aus. Dafür muss ich vermutlich die  Gruppierung aufheben und neu gruppieren?

Ist wahrscheinlich technisch ein bisschen zu aufwendig das dynamisch zu machen, also die Reihenfolge im Accordeon?

**Comment by rlucke** [comment]
Da hast du Recht, man muss im Moment zwei Mal speichern. Das ist etwas unglücklich!
