### ISSUE TITLE
Dateibereich: Courseware-Ordner

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#171]
Oft sollen Dateien die in Courseware verwendet werden nicht im Dateibereich erscheinen. Hierfür wird ein Ordner benötigt der nur für den Lehrenden sichtbar ist. Inhalte des Ordners sollen aber für die Teilnehmer zugänglich sein.

**Comment by elorie** [comment]
Dafür bietet Stud.Ip selber die Funktion "unsichtbarer Ordner".

**Comment by rlucke** [comment]
Die Funktionin dem gewünschten Sinne ist aber erst ab Stud.IP 4.5 verfügbar!

**Comment by nimuelle** [comment]
Wenn Lehrende Materialien in einem unsichtbaren Ordner (innerhalb der VA) nutzen/verlinken, dann sehen auch nur die Lehrenden diese Inhalte, Studierende würden das nicht sehen.

**Comment by rlucke** [comment]
Da Courseware V ab Stud.IP 4.5 verfügbar sein wird sind keine weiteren Aktionen notwendig.
