### ISSUE TITLE
embedding funktioniert in diversen Browsern nicht

### ISSUE THREAD

**Issue by JFD23** [virtUOS/courseware#181]
in Safari auf Mac und in Edge unter Windows funktioniert das Embedding in z.B. Anküdigungen über den Opencast Tag nicht. In Edge zeigt er eine Warnung an, dass der Herausgeber die Darstellung eines iFrames nicht gestattet. In Safari bleibt die Viewbox einfach weiß.

same issue in studip-opencast-plugin [studip-opencast-plugin](https://github.com/elan-ev/studip-opencast-plugin/issues/160)

**Comment by rlucke** [comment]
Fehlerhaftes verhalten in Edge und Safari konnte ich nicht reproduzieren. Nach Rücksprache mit dem OpenCast-Team habe ich entschieden sowohl den Theodul als auch den Paella Player anzubieten. Der OpenCastBlock wird entsprechend umgebaut.
