### ISSUE TITLE
Interaktive Darstellungen auch bei Bilder

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#182]
Es wäre schön, wenn man auch bei Bildern, kleine Fenster (Dialoge) platzieren könnte (oben rechts, links, mittig etc.). In diesen Fenstern kann Text und/oder Links zu anderen Kapiteln/Abschnitten/Blöcken oder nur eine URL hinterlegt werden.

![Startbild](https://user-images.githubusercontent.com/1579150/58233739-26445400-7d3d-11e9-8d97-6ec708b49c1c.PNG)

**Comment by rlucke** [comment]
Die Idee finde ich sehr spannend. Grundsätzlich ist dies dann aber ein neuer Blocktype. 
Für die Autorenumgebung kann ich mir ein Canvas vorstellen, ähnlich wie beim Leinwand-Block. Man kann dann Texte einfügen oder Bereiche markieren. Unter dem Bild wird dann eine Liste mit den Elementen angezeigt. Den Elementen können verschiedene Events zugeordnet werden, z.B. Links, Overlays etc.
