### ISSUE TITLE
Kleiner Fehler bei Hover "Kapitel sortieren"

### ISSUE THREAD

**Issue by JFD23** [virtUOS/courseware#188]
Das Umschalten background-images beim Hovern klappt nicht. Das weiße Icon bleibt unsichtbar. Hier die betroffene Code-Stelle in der buttons.less

  &.init-sort-chapter,
  &.init-sort-subchapter,
  &.init-sort-section {
    background-image: url("../../assets/images/icons/blue/arr_1sort.svg");
    background-position: 6px center;
    &:hover {
        background-image: url("../../assets/images/icons/white/arr_1sort.svg");
    }
  }

**Comment by rlucke** [comment]
Da scheint die SVG kaputt zu sein!

**Comment by JFD23** [comment]
Danke für den fixen fix ;-)
bei mir geht es auch nach deinem fix leider nicht :-(
