### ISSUE TITLE
stylesheet bug in "Letzte Änderungen"

### ISSUE THREAD

**Issue by JFD23** [virtUOS/courseware#195]
Videovorschaubilder ragen über Kästchen hinaus. 
Kästchen in der zweiten Reihe springen durch die Gegend je nach Mauszeiger.

**Comment by JFD23** [comment]
![Uploading Bildschirmfoto 2019-12-05 um 11.17.34.png…]()

**Comment by rlucke** [comment]
Das IFrame wird nocht nicht angepasst. Dafür wird ein fix geschrieben, kommt dann in die 4.5.1
