### ISSUE TITLE
Block: Verweissensitive Grafik

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#197]
Idee: Manchmal will man keinen Link dafür haben, sondern nur einen Tooltipp. Der Tooltipp geht zwar, aber nur weil man keinen Link hinterlegt.Ist der Block ganz unten und man klickt drauf, springt man ganz nach oben. Gut wäre eine Art Schalter "Nur den Tooltipp anzeigen".

Und wenn man eine geom. Figur ausgewählt hat, kann man diese zwar befüllen, aber keinen Rahmen anzeigen (so dass der Rest tranparent ist, aber der Rahmen da).
Das wäre auch noch sinnvoll, wenn man auch Rahmen sehen könnte

**Comment by rlucke** [comment]
move to Courseware V
