### ISSUE TITLE
Vips-Aufgaben-Typ vor Anzeige prüfen

### ISSUE THREAD

**Issue by tthelen** [virtUOS/courseware#20]
Der Vips-Aufgabentyp (Selbsttest, Klausur, ...) kann sich nach dem erstmaligen Einbinden ändern. Um daraus resultierende unerwünschte Effekte abzufangen, soll vor jeder Anzeige geprüft werden, ob der Einbindungstyp dem Vips-Blatt-Typ entspricht und widrigenfalls eine Fehlermeldung angezeigt werden.

**Comment by rlucke** [comment]
Wie soll die Fehlermeldung lauten?
Mein Vorschlag wäre:
"Der Aufgabentyp hat sich geändert. Bitte wenden Sie sich an Ihren Dozenten."

**Comment by rlucke** [comment]
gelöst im Branch "testblock"

**Comment by rlucke** [comment]
gelöst
