### ISSUE TITLE
Kommentare ausblenden im Seitenblock

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#204]
Ist  "Kommentare & Diskussionen"-Block  als Seitenblock eingebunden, führt das Ausblenden von Kommentaren in der Fortschrittsübersicht dazu, dass alle Kommentare ausgeblendet werden.

<img width="1006" alt="Bildschirmfoto 2020-04-23 um 14 51 10" src="https://user-images.githubusercontent.com/64207148/80103221-2dd73300-8574-11ea-947c-6a6899e5feeb.png">

<img width="518" alt="Bildschirmfoto 2020-04-23 um 14 52 59" src="https://user-images.githubusercontent.com/64207148/80103061-ed77b500-8573-11ea-8745-228f49752597.png">

**Comment by rlucke** [comment]
Dieser Fehler betraf nicht nur die Sidebar. Wurde in Version 4.5.3 gelöst!
