### ISSUE TITLE
Import Dateien "Verweissensitive Grafik"

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#211]
Die Dateien für die "Verweissensitive Grafik" werden nicht in den Dateibereich mitimportiert, wenn man eine Courseware aus einem Import-Archiv importiert.

Beim "Import aus Veranstaltung" hingegen werden die Dateien der verweissensitiven Grafiken mit in den Dateibereich importiert.

Courseware-Version: 4.6.1

**Comment by rlucke** [comment]
Dieser Fehler lässt sich leider bei mir nicht reproduzieren.
