### ISSUE TITLE
Import aus Veranstaltung nur, wenn schon Kapitel vorhanden

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#212]
Das Feature "Aus Veranstaltung importieren" funktioniert nur, wenn bereits ein Kapitel vorhanden ist. Ist die Courseware leer, werden die ausgewählen Kapitel nicht importiert.

Courseware-Version: 4.6.1

**Comment by rlucke** [comment]
Empty dropable list has to be an array not an object!
