### ISSUE TITLE
Bezeichnung des Links wird nicht angezeigt

### ISSUE THREAD

**Issue by nafetsohste** [virtUOS/courseware#214]
bei der Ausgestaltung eines Courseware-Angebots tritt folgendes Problem auf:

Wenn ein Block „Link“ – wie im Screenshot angezeigt – ausgefüllt wird, ...

![image](https://user-images.githubusercontent.com/7033324/91409727-1e2f6a00-e846-11ea-9300-7c16af868f0d.png)

... wird die Bezeichnung des Links sowohl im Lese- als auch Bearbeitungsmodus nicht angezeigt.

![image](https://user-images.githubusercontent.com/7033324/91409774-2daeb300-e846-11ea-8fd0-93f7794b5b58.png)

**Comment by rlucke** [comment]
Bei dieser speziellen URL wird nichts angezeigt, weil die gelieferten OpenGraph Inhalte leer sind.
Der LinkBlock unterscheidet derzeit ob OpenGraph unterstützt wird oder nicht. Falls ja werden die Informationen von OpenGraph dargestellt, falls nicht wird der gesetzte Titel angezeigt.
Es ist offenbar sinnvoll und notwendig diese Möglichkeit optional zu machen.
