### ISSUE TITLE
Zuordnungsaufgaben in Akkordiontestblöcken

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#22]
Befinden sich Zuordnungsaufgaben in Akkordiontestblöcken nicht auf Seite 1, werden die Höhen der zuzuordnenden Elemente nicht korrekt ermittelt. Diese Elemente erscheinen dann versetzt. Nach dem ersten Ansortieren, ist dann wieder alles korrekt.

**Comment by noesting** [comment]
solved in https://github.com/virtUOS/courseware/pull/70
