### ISSUE TITLE
Unterkapitel und Abschnitte trotz entzogener Leserechte erreichbar

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#223]
Wenn ein Unterkapitel oder Abschnitt an erster Stelle steht gelangt man über die Navigation des Kapitels bzw des Unterkapitels zum entsprechenden Abschnitt. Der Inhalt wird zwar nicht angezeigt, aber Navigationselemente und Breadcrumb schon.

Außerdem erscheinen Elemente die in nicht erreichbaren struktur Elementen enthalten sind in der Letzte Änderungen Übersicht.

**Comment by dennis531** [comment]
Zudem navigiert idie"Pfeil"-Navigation auf nicht lesbare Abschnitte, Kapitel und Unterkapitel.
