### ISSUE TITLE
Miro in den Embed-Block aufnehmen

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#226]
Ist es möglich, https://miro.com/ mit in den embed-Block aufzunehmen?

**Comment by rlucke** [comment]
Der Embed-Block nutzt oembed (https://oembed.com/). Wenn miro eine entsprechende Schnittstelle hat kann es gerne mit aufgenommen werden.

**Comment by rlucke** [comment]
Offenbar wird nur der iFrame Weg bei miro unterstützt, also empfehle ich den entsprechenden Block zu verwenden.
