### ISSUE TITLE
Abschnitts-Symbole importieren

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#228]
Beim Ex- und Import gehen zugewiesene Abschnittssymbole verloren.
Besser wäre, wenn händisch eingestellte Abschnittssymbole beim Import erhalten bleiben.

**Comment by rlucke** [comment]
Beim Drag&Drop Import / Export werden die Icons übernommen. Für den Im- & Export über Archive müsste dies realisiert werden.
