### ISSUE TITLE
Import Interactive Video verweist auf alten Dateibereich

### ISSUE THREAD

**Issue by vermayer** [virtUOS/courseware#230]
Importiert man eine Courseware mit einem interaktiven Video, das im Dateibereich abgelegt war, verweist das "neue" interaktive Video auf eine "Datei im Dateibereich anderer Nutzer". Die URL bleibt weiter die die URL des Videos in der alten Courseware.
Nchtsdestotrotz wird das Video mit in den neuen Dateibereich importiert, nur die Verlinkung in der Courseware ändert sich nicht.

**Comment by rlucke** [comment]
Der Fehler liegt in den vorhandenen und somit auch in den exportierten Daten. Der Dateiname kann nicht verglichen werden, weil dieser nicht gesetzt wurde, somit kann die neue File ID auch nicht gesetzt werden.
Der Fix setzt die Daten jetzt richtig in die Datenbank, wenn man den Block speichert. Daten die bereits in der Datenbank stehen werden nicht geändert. Es muss also der Block noch einmal zum bearbeiten geöffnet und gespeichert werden. Danach gelangen die notwendigen Daten auch in den Export und der Import gelingt.
