### ISSUE TITLE
Blubber-Fehler bei Stud.IP 4.6

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#236]
Wenn ich den Blubber-Block aktivere über die Verwaltung, kann ich die Coureseware danach nicht mehr nutzen, es kommt dieser Fehler:

``
2021/03/03 11:54:13 [error] 22154#22154: *26163 FastCGI sent in stderr: "PHP message: Error: Class 'BlubberPosting' not found in /mnt/data/devel13/studip-4.6/public/plugins_packages/virtUOS/Courseware/blocks/DiscussionBlock/Discussion.php:35
Stack trace:
#0 /mnt/data/devel13/studip-4.6/public/plugins_packages/virtUOS/Courseware/blocks/DiscussionBlock/Discussion.php(14): Mooc\UI\DiscussionBlock\Discussion->findOrCreateBlubberThread()
#1 /mnt/data/devel13/studip-4.6/public/plugins_packages/virtUOS/Courseware/blocks/DiscussionBlock/GroupDiscussion.php(16): Mooc\UI\DiscussionBlock\Discussion->__construct('f261baddf8191e9...', Object(Courseware\User))
#2 /mnt/data/devel13/studip-4.6/public/plugins_packages/virtUOS/Courseware/blocks/DiscussionBlock/DiscussionBlock.php(116): Mooc\UI\DiscussionBlock\GroupDiscussion->__construct('f261baddf8191e9...', Object(Courseware\User), '234626', NULL)
#3 /mnt/data/devel13/studip-4.6/public/plugins_packages/virtUOS/Courseware/blocks/DiscussionBlock/DiscussionBlock.php(104): Mooc\UI\DiscussionBlock\DiscussionBlock->getThreadsOfUserInAll()
#4 /mnt/d" while reading response header from upstream, client: 134.106.105.236, server: .., request: "GET /46/plugins.php/courseware/courseware?cid=f261baddf8191e97680ab1e4b1ffcd1f HTTP/1.1", upstream: "fastcgi://unix:/var/run/php-fpm.sock:", host: "devel13.elearning.uni-oldenburg.de", referrer: ".../46/plugins.php/courseware/courseware?cid=f261baddf8191e97680ab1e4b1ffcd1f"
``

**Comment by rlucke** [comment]
fixed in master46
