### ISSUE TITLE
Fehler beim PDF-Viewer-Block

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#238]
Es gibt PDF's mit Latex-Formeln, die zwar im normalen PDF-Viewer korrekt aussehen, jedoch im PDF-Viewer von CW, "verstückelt."

![image](https://user-images.githubusercontent.com/1579150/111289990-fb2fa080-8645-11eb-9f58-1963a25e657a.png)

**Comment by nimuelle** [comment]
der Fehler tritt sowohl in 4.6.x als auch in 4.8.x auf...

**Comment by rlucke** [comment]
fixed with commit 4e86e5fd3426b7d0930c49a54a145b4acca4ff18
