### ISSUE TITLE
Aufgaben-IDs können mehrmals pro Seite auftauchen

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#24]
Früher und auch nach c7ef664 besteht immer noch die Möglichkeit, dass Aufgaben mehrfach pro Seite angezeigt werden können. Dann wären die IDs nicht mehr eindeutig und es würde zu Problemen kommen.

**Comment by rlucke** [comment]
gelöst in testblock branch

**Comment by rlucke** [comment]
gelöst

**Comment by rlucke** [comment]
Das Javascript sucht nur innerhalb des Blocks nach der ID. Sicher keine ideale Lösung, aber negative Effekte treten daher im Moment nicht auf.
