### ISSUE TITLE
2. Fehler bem Audio-Galerie-Block (Version 4.8.X)

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#247]
1. Der Ordner "Coursware-Upload" (Profil > Meine Dateien) hat den falschen Ordnertyp. Nur man selbst hört seine Audionachricht. (Der Ordnertyp müsste eigentlich "öffentlich zugängliche Daten" sein.

2. Wenn ich eine Audiospur aufnehmen, dann wird nur ca. 1/4 wiedergegeben. Nehme ich 30 Sekunden auf, werden 8 Sek abgespielt. Nehme ich 1.10 Minute auf, sehe ich  0.18 sek.

**Comment by rlucke** [comment]
Der zweite Fehler ist ein Browserproblem. Bei Firefox genügt ein Update auf die aktuellste Version.
Mir ist hierbei ein grundlegendes Safari-Problem aufgefallen, dies wird seperat behandelt.
