### ISSUE TITLE
Fehler beim Selbsttest-Block (Version 4.8.x)

### ISSUE THREAD

**Issue by nimuelle** [virtUOS/courseware#248]
Lege ich in Vips einen Selbsttest mit Aufgabentyp Freitext an und sage "3 Versuche", dann steht schon nach dem ersten Versuch "Danke fürs Teilnehmen" und die hinterlegte Musterlösung wird nicht angezeigt.

**Comment by rlucke** [comment]
Und wieso ist das falsch?
Textaufgaben können nicht automatisch bewertet werden. In einem Selbsttest kann somit von Vips weder falsch noch richtig geliefert werden. Um sich selber zu überprüfen muss man seine Lösung mit der Musterlösung vergleichen. Mehrfaches abschicken (Versuche) ändern diesen Umstand nicht.
