### ISSUE TITLE
Safari Countdown aN

### ISSUE THREAD

**Issue by phunstack** [virtUOS/courseware#249]
In Safari (getestet mit 14.0.3.) erscheint der Countdown mit Fehlern. Brauchen Sie noch weitere Informationen oder ist Safari generell nicht unterstützt?

Screenshot:
![grafik](https://user-images.githubusercontent.com/73217312/114838743-4ec41400-9dd5-11eb-9190-58bd86200b26.png)

**Comment by phunstack** [comment]
Was ist der Grund für das closed?

**Comment by rlucke** [comment]
Dieser Fix!
https://github.com/virtUOS/courseware/commit/4c444072434626525470e115a49d3a73fe1ac829
