### ISSUE TITLE
CW 5 Migration VideoBlock

### ISSUE THREAD

**Issue by Superjamp** [virtUOS/courseware#269]
Es gibt bei uns alte VideoBlock's ohne source in json_data, bei diesen wird der Block nicht migiert.

Idee:
```
if ($webvideo->source === 'url' || $webvideo->source === NULL) {
```

Problemstelle:
https://github.com/virtUOS/courseware/blob/5ec32abb9334dc24984474cbbfb6fc7f64435317/command/MigrateCoursewareCommand.php#L692-L715

**Comment by rlucke** [comment]
Ist in 5.0.9 behoben.
