### ISSUE TITLE
Kompatibilitätsfunktionen entfernen

### ISSUE THREAD

**Issue by luniki** [virtUOS/courseware#28]
Mooc.IP war auf Stud.IP < v3.1 ausgelegt. Courseware beinhaltete dazu Funktionen, um Fehlendes ggfs zu ergänzen. Bitte entfernen!

**Comment by xabbuh** [comment]
@luniki `studipMinVersion` in `plugin.manifest` müsste dann auch noch erhöht werden, oder?

**Comment by luniki** [comment]
hmm stimmt, guter Plan
