### ISSUE TITLE
Ordnerblock zeigt unsichtbaren Ordner nicht an obwohl Downloads erlaubt sind

### ISSUE THREAD

**Issue by AaronWiora** [virtUOS/courseware#280]
Folgendes Feedback haben wir erhalten:

> Bindet man in der Courseware im Block "Datei-Ordner" einen Ordner ein, der zwar unsichtbar ist, aber den Zugriff auf Dateien per Link erlaubt, können die Studierenden die Dateien in der Courseware nicht sehen. Dozent* innen werden die Dateien angezeigt.  Für User ist diese Logik allerdings nicht nachvollziehbar. Wenn der Zugriff auf Dateien via Link im Ordner-Menü erlaubt wird, dann müssten in dieser Einbindung eines unsichtbaren Ordners im Block "Datei-Ordner" auch die darin enthaltenen Dateien angezeigt werden

Ich wollte mir das erstmal selber ansehen und habe in der Datei blocks/FolderBlock/FolderBlock.php:37 etwas gefunden was mir relevant erscheint:
```
public function student_view()
    {
      ...
            switch ($folder_type) {
                case 'HiddenFolder':
                    if($folder->data_content['download_allowed'] != 1) {
                        $folder_hidden = true;
                    }
                    break;
```
Ich stecke im Code des Plugins nicht wirklich drin aber dieser Fall scheint ja zumindest bedacht worden zu sein.

**Comment by rlucke** [comment]
Ich kann verstehen, dass dieses Verhalten auf den ersten Blick nicht ganz schlüssig ist. Aber es wird vom OrdnerBlock genau das gleiche Verhalten des Ordners abgebildet, welches er auch im Dateibereich hat. Teilnehmende haben weder die Freigabe "isVisible" noch "isReadable", daher wird die Ausgabe der Dateien nicht ausgeführt.
