### ISSUE TITLE
Nichtlineare Freigabe lässt Navigation verschwinden

### ISSUE THREAD

**Issue by anantace** [virtUOS/courseware#58]
Wenn man die Kapitel in nichtlinearer Reihenfolge freigibt, oder ein einzelnes Kapitel (nicht das letzte) zu einem späteren Zeitpunkt freigibt, gibt es in der Nutzeransicht keine Coursewarenavigation mehr.

Es sollte also entweder  
- so angepasst werden, dass das System mit einer nicht-linearen Freigabe klar kommt oder
- auf technischer Ebene verhindert werden
  - zB. Wenn Kapitel C erst ab 17.12. sichtbar ist dann wird die Einstellung automatisch für alle darauffolgenden Kapitel übernommen und kann nicht auf einen davor liegenden Zeitpunkt gesetzt werden  

Bsp.:  
Heute ist der 14.03.
Kapitel 1 (keine Angabe, also ab heute, 14.03.)
Kapitel 2 (keine Angabe, also ab heute, 14.03.)
Kapitel 3: 15.3. (mit extra Angabe)
Kapitel 4: (keine Angabe, also ab heute, 14.03.)
Kapitel 5: 17.6. (mit extra Angabe)  
  
Problem: Kapitel 3 ist erst nach Kapitel 4 sichtbar

**Comment by luniki** [comment]
Ok, das ist wieder einmal ein doofes mustache-Problem.
