### ISSUE TITLE
"Fortschrittsübersicht" ohne aktiviertes Courseware

### ISSUE THREAD

**Issue by noesting** [virtUOS/courseware#60]
Der Reiter "Fortschrittsübersicht" erscheint in einer als MOOC-artig angelegten Veranstaltung, auch ohne Courseware der Veranstaltung hinzugefügt zu haben. Ein Klick auf den Reiter führt zu einer leeren Seite mit der Ausgabe "400 No route matches 'progress'"

**Comment by noesting** [comment]
Scheint aufzutauchen, wenn als Plugin der Veranstaltung Mooc.IP aber nicht Courseware aktiviert ist.

**Comment by tthelen** [comment]
Prüf mal, wo die "Fortschrittsübersicht" überhaupt steckt - im 
Courseware-Plugin oder im MOOC.IP-Plugin. Sie gehört zur Courseware, 
aber die Navigationsposition ist wohl nicht optimal.

Am 23.03.2016 um 11:44 schrieb noesting:
>
> Scheint aufzutauchen, wenn als Plugin der Veranstaltung Mooc.IP aber 
> nicht Courseware aktiviert ist.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/virtUOS/courseware/issues/60#issuecomment-200291997>
>

-- 
-----------------------------------------------------------
Dr. Tobias Thelen           tobias.thelen@uni-osnabrueck.de
Zentrum virtUOS             Tel. (auch mobil) 0541/969-6502
                                                 Fax: -16502
Zentrum  für  Informationsmanagement  und  virtuelle  Lehre
             http://www.virtuos.uni-osnabrueck.de
Heger-Tor-Wall 12,  Universität Osnabrück,  49069 Osnabrück

**Comment by noesting** [comment]
Das Problem scheint im Mooc-Plugin in Mooc.php zu liegen:

    public function getTabNavigation($course_id)
    {
        $tabs = array();

        if ($this->isSlotModule()) {
            $tabs['mooc_overview']   = $this->getOverviewNavigation();
        }

        if (!$this->container['current_user']->hasPerm($course_id, 'dozent')) {
            $progress_url = PluginEngine::getURL($this, compact('cid'), 'progress', true);
            $tabs['mooc_progress'] = new Navigation(_('Fortschrittsübersicht'), $progress_url);
        }

        return $tabs;
    }


Wenn man da $tabs['mooc_progress'] = new Navigation(_('Fortschrittsübersicht'), $progress_url); auskommentiert, wird der Tab bei deaktivierter Courseware und aktiviertem Mooc-Plugin nicht mehr angezeigt. Die Frage ist, warum komme ich da als test_autor rein?

**Comment by tthelen** [comment]
Hi Nils,

ruf mich doch mal grad unter 6502 an! (dauert etwas wg. Handy-Weiterleitung)

Ciao,
Tobias

Am 23.03.2016 um 15:11 schrieb Nils Oesting:
>
> Das Problem scheint im Mooc-Plugin in Mooc.php zu liegen:
>
> |public function getTabNavigation($course_id) { $tabs = array(); if 
> ($this->isSlotModule()) { $tabs['mooc_overview'] = 
> $this->getOverviewNavigation(); } if 
> (!$this->container['current_user']->hasPerm($course_id, 'dozent')) { 
> $progress_url = PluginEngine::getURL($this, compact('cid'), 
> 'progress', true); $tabs['mooc_progress'] = new 
> Navigation(_('Fortschrittsübersicht'), $progress_url); } return $tabs; } |
>
> Wenn man da $tabs['mooc_progress'] = new 
> Navigation(_('Fortschrittsübersicht'), $progress_url); auskommentiert, 
> wird der Tab bei deaktivierter Courseware und aktiviertem Mooc-Plugin 
> nicht mehr angezeigt. Die Frage ist, warum komme ich da als test_autor 
> rein?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub 
> <https://github.com/virtUOS/courseware/issues/60#issuecomment-200360415>
>

-- 
-----------------------------------------------------------
Dr. Tobias Thelen           tobias.thelen@uni-osnabrueck.de
Zentrum virtUOS             Tel. (auch mobil) 0541/969-6502
                                                 Fax: -16502
Zentrum  für  Informationsmanagement  und  virtuelle  Lehre
             http://www.virtuos.uni-osnabrueck.de
Heger-Tor-Wall 12,  Universität Osnabrück,  49069 Osnabrück

**Comment by tthelen** [comment]
Da steht NOT dozent, ist also von der Logik her richtig. Falsch ist, dass die Fortschrittsansicht über haupt im Mooc.IP-Plugin ist, weil sie ausschließlich auf Courseware-Informationen zugreift.

**Comment by noesting** [comment]
https://github.com/virtUOS/mooc.ip/issues/384
