### ISSUE TITLE
Sortieren und Kopieren von Unterkapiteln und Abschnitten

### ISSUE THREAD

**Issue by tthelen** [virtUOS/courseware#69]
Es wäre sehr schön wenn man Unterkapitel auch in andere Kapitel verschieben könnte. Die gleiche Freiheit wäre auch für Abschnitte wünschenswert. Auch eine Kopierfunktion von Abschnitten und Unterkapiteln wäre hilfreich.

**Comment by rlucke** [comment]
Will be solved in #108
