### ISSUE TITLE
Export mit Bildern in Vips

### ISSUE THREAD

**Issue by asudau** [virtUOS/courseware#88]
Wenn man eine Vipsaufgabe mit Bildern hat wird diese nicht korrekt exportiert/importiert.  
Die Bilder müssen mitkopiert und die Links entsprechend angepasst werden.

**Comment by rlucke** [comment]
Da Vips in Zukunft seinen eigenen CW-Block bereitstellen wird kümmert sich Vips in Zukunft um dieses Problem.
