### ISSUE TITLE
Suchfunktion (Suchblock)

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#92]
Courseware-Inhalte sollen durchsucht werden können. Die Suchergebnisse werden auf einer Ergebnisseite aufgelistet (vgl. Wiki-Suche). Blöcke, die ihre Inhalte nicht direkt in den Courseware-Block-
Daten ablegen (z.B. Vips) sollen ein Interface bekommen, um die verbundenen Inhalte durchsuchen zu können.

**Comment by tthelen** [comment]
"Titel" in "Überschrift" ändern.

Suchergebnisse: Wenn ich nach "Abschnitt suche", bekomme ich viel mehr Treffer als Abschnitte mit Überschrift "Abschnitt" - warum?

**Comment by rlucke** [comment]
Es wurden auch Strukturblöcke mit Null als seminar_id ausgewählt. Der Fehler ist behoben.
