### ISSUE TITLE
Akkordeon-Block

### ISSUE THREAD

**Issue by rlucke** [virtUOS/courseware#99]
Mit dieser Änderung soll ein Container-Block geschaffen werden, der mehrere Blöcke beinhaltet und mit einer Akkordeon-Ansicht (alle Überschriften sind immer sichtbar, aber nur der gerade ausgewählte Block wird komplett dargestellt) verbunden ist.

**Comment by rlucke** [comment]
erledigt in develop22

**Comment by tthelen** [comment]
Schön wäre noch irgendein Hinweis, der die Block-ID etwas sinnvollem zuordenbar macht (z.B. Blocktyp und Anfang des Textes bei Freitextblöcken, sonst eben auch Titel)
